language: python
os: linux
dist: focal

python:
  - 3.8.6

services:
  - postgresql

addons:
  postgresql: '12'
  apt:
    packages:
    - postgresql-12
    - postgresql-client-12

env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1
    - PGPORT=5433

before_script:
  - psql -c 'CREATE DATABASE testdb;' -U postgres

install:
  - pip install pipenv
  - pip install codecov
  - pipenv sync -d
  - cp contrib/env-sample .env

script:
  - pipenv run flake8 .
  - pipenv run pytest vbl_teste_django --cov=vbl_teste_django

after_success:
  - codecov